// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: click.proto

#ifndef PROTOBUF_click_2eproto__INCLUDED
#define PROTOBUF_click_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protocol {
namespace share {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_click_2eproto();
void protobuf_AssignDesc_click_2eproto();
void protobuf_ShutdownFile_click_2eproto();

class ClickRequest;
class ClickResponse;

// ===================================================================

class ClickRequest : public ::google::protobuf::Message {
 public:
  ClickRequest();
  virtual ~ClickRequest();

  ClickRequest(const ClickRequest& from);

  inline ClickRequest& operator=(const ClickRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClickRequest& default_instance();

  void Swap(ClickRequest* other);

  // implements Message ----------------------------------------------

  ClickRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClickRequest& from);
  void MergeFrom(const ClickRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string cookiesId = 1;
  inline bool has_cookiesid() const;
  inline void clear_cookiesid();
  static const int kCookiesIdFieldNumber = 1;
  inline const ::std::string& cookiesid() const;
  inline void set_cookiesid(const ::std::string& value);
  inline void set_cookiesid(const char* value);
  inline void set_cookiesid(const char* value, size_t size);
  inline ::std::string* mutable_cookiesid();
  inline ::std::string* release_cookiesid();
  inline void set_allocated_cookiesid(::std::string* cookiesid);

  // @@protoc_insertion_point(class_scope:protocol.share.ClickRequest)
 private:
  inline void set_has_cookiesid();
  inline void clear_has_cookiesid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* cookiesid_;
  friend void  protobuf_AddDesc_click_2eproto();
  friend void protobuf_AssignDesc_click_2eproto();
  friend void protobuf_ShutdownFile_click_2eproto();

  void InitAsDefaultInstance();
  static ClickRequest* default_instance_;
};
// -------------------------------------------------------------------

class ClickResponse : public ::google::protobuf::Message {
 public:
  ClickResponse();
  virtual ~ClickResponse();

  ClickResponse(const ClickResponse& from);

  inline ClickResponse& operator=(const ClickResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ClickResponse& default_instance();

  void Swap(ClickResponse* other);

  // implements Message ----------------------------------------------

  ClickResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClickResponse& from);
  void MergeFrom(const ClickResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string cookiesId = 1;
  inline bool has_cookiesid() const;
  inline void clear_cookiesid();
  static const int kCookiesIdFieldNumber = 1;
  inline const ::std::string& cookiesid() const;
  inline void set_cookiesid(const ::std::string& value);
  inline void set_cookiesid(const char* value);
  inline void set_cookiesid(const char* value, size_t size);
  inline ::std::string* mutable_cookiesid();
  inline ::std::string* release_cookiesid();
  inline void set_allocated_cookiesid(::std::string* cookiesid);

  // @@protoc_insertion_point(class_scope:protocol.share.ClickResponse)
 private:
  inline void set_has_cookiesid();
  inline void clear_has_cookiesid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* cookiesid_;
  friend void  protobuf_AddDesc_click_2eproto();
  friend void protobuf_AssignDesc_click_2eproto();
  friend void protobuf_ShutdownFile_click_2eproto();

  void InitAsDefaultInstance();
  static ClickResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// ClickRequest

// optional string cookiesId = 1;
inline bool ClickRequest::has_cookiesid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ClickRequest::set_has_cookiesid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ClickRequest::clear_has_cookiesid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ClickRequest::clear_cookiesid() {
  if (cookiesid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cookiesid_->clear();
  }
  clear_has_cookiesid();
}
inline const ::std::string& ClickRequest::cookiesid() const {
  // @@protoc_insertion_point(field_get:protocol.share.ClickRequest.cookiesId)
  return *cookiesid_;
}
inline void ClickRequest::set_cookiesid(const ::std::string& value) {
  set_has_cookiesid();
  if (cookiesid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cookiesid_ = new ::std::string;
  }
  cookiesid_->assign(value);
  // @@protoc_insertion_point(field_set:protocol.share.ClickRequest.cookiesId)
}
inline void ClickRequest::set_cookiesid(const char* value) {
  set_has_cookiesid();
  if (cookiesid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cookiesid_ = new ::std::string;
  }
  cookiesid_->assign(value);
  // @@protoc_insertion_point(field_set_char:protocol.share.ClickRequest.cookiesId)
}
inline void ClickRequest::set_cookiesid(const char* value, size_t size) {
  set_has_cookiesid();
  if (cookiesid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cookiesid_ = new ::std::string;
  }
  cookiesid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:protocol.share.ClickRequest.cookiesId)
}
inline ::std::string* ClickRequest::mutable_cookiesid() {
  set_has_cookiesid();
  if (cookiesid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cookiesid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:protocol.share.ClickRequest.cookiesId)
  return cookiesid_;
}
inline ::std::string* ClickRequest::release_cookiesid() {
  clear_has_cookiesid();
  if (cookiesid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = cookiesid_;
    cookiesid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ClickRequest::set_allocated_cookiesid(::std::string* cookiesid) {
  if (cookiesid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete cookiesid_;
  }
  if (cookiesid) {
    set_has_cookiesid();
    cookiesid_ = cookiesid;
  } else {
    clear_has_cookiesid();
    cookiesid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.share.ClickRequest.cookiesId)
}

// -------------------------------------------------------------------

// ClickResponse

// required string cookiesId = 1;
inline bool ClickResponse::has_cookiesid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ClickResponse::set_has_cookiesid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ClickResponse::clear_has_cookiesid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ClickResponse::clear_cookiesid() {
  if (cookiesid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cookiesid_->clear();
  }
  clear_has_cookiesid();
}
inline const ::std::string& ClickResponse::cookiesid() const {
  // @@protoc_insertion_point(field_get:protocol.share.ClickResponse.cookiesId)
  return *cookiesid_;
}
inline void ClickResponse::set_cookiesid(const ::std::string& value) {
  set_has_cookiesid();
  if (cookiesid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cookiesid_ = new ::std::string;
  }
  cookiesid_->assign(value);
  // @@protoc_insertion_point(field_set:protocol.share.ClickResponse.cookiesId)
}
inline void ClickResponse::set_cookiesid(const char* value) {
  set_has_cookiesid();
  if (cookiesid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cookiesid_ = new ::std::string;
  }
  cookiesid_->assign(value);
  // @@protoc_insertion_point(field_set_char:protocol.share.ClickResponse.cookiesId)
}
inline void ClickResponse::set_cookiesid(const char* value, size_t size) {
  set_has_cookiesid();
  if (cookiesid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cookiesid_ = new ::std::string;
  }
  cookiesid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:protocol.share.ClickResponse.cookiesId)
}
inline ::std::string* ClickResponse::mutable_cookiesid() {
  set_has_cookiesid();
  if (cookiesid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cookiesid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:protocol.share.ClickResponse.cookiesId)
  return cookiesid_;
}
inline ::std::string* ClickResponse::release_cookiesid() {
  clear_has_cookiesid();
  if (cookiesid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = cookiesid_;
    cookiesid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ClickResponse::set_allocated_cookiesid(::std::string* cookiesid) {
  if (cookiesid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete cookiesid_;
  }
  if (cookiesid) {
    set_has_cookiesid();
    cookiesid_ = cookiesid;
  } else {
    clear_has_cookiesid();
    cookiesid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:protocol.share.ClickResponse.cookiesId)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace share
}  // namespace protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_click_2eproto__INCLUDED
