// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: click.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "click.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace protocol {
namespace share {

namespace {

const ::google::protobuf::Descriptor* ClickRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClickRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* ClickResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClickResponse_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_click_2eproto() {
  protobuf_AddDesc_click_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "click.proto");
  GOOGLE_CHECK(file != NULL);
  ClickRequest_descriptor_ = file->message_type(0);
  static const int ClickRequest_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClickRequest, cookiesid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClickRequest, age_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClickRequest, sex_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClickRequest, geoinfo_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClickRequest, adinfo_),
  };
  ClickRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ClickRequest_descriptor_,
      ClickRequest::default_instance_,
      ClickRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClickRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClickRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ClickRequest));
  ClickResponse_descriptor_ = file->message_type(1);
  static const int ClickResponse_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClickResponse, cookiesid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClickResponse, age_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClickResponse, sex_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClickResponse, geoinfo_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClickResponse, adinfo_),
  };
  ClickResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ClickResponse_descriptor_,
      ClickResponse::default_instance_,
      ClickResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClickResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClickResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ClickResponse));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_click_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ClickRequest_descriptor_, &ClickRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ClickResponse_descriptor_, &ClickResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_click_2eproto() {
  delete ClickRequest::default_instance_;
  delete ClickRequest_reflection_;
  delete ClickResponse::default_instance_;
  delete ClickResponse_reflection_;
}

void protobuf_AddDesc_click_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protocol::share::protobuf_AddDesc_common_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013click.proto\022\016protocol.share\032\014common.pr"
    "oto\"\215\001\n\014ClickRequest\022\021\n\tcookiesId\030\001 \001(\t\022"
    "\013\n\003age\030\002 \001(\005\022\013\n\003sex\030\003 \001(\005\022(\n\007geoInfo\030\004 \001"
    "(\0132\027.protocol.share.GeoInfo\022&\n\006adInfo\030\005 "
    "\001(\0132\026.protocol.share.AdInfo\"\216\001\n\rClickRes"
    "ponse\022\021\n\tcookiesId\030\001 \002(\t\022\013\n\003age\030\002 \001(\005\022\013\n"
    "\003sex\030\003 \001(\005\022(\n\007geoInfo\030\004 \001(\0132\027.protocol.s"
    "hare.GeoInfo\022&\n\006adInfo\030\005 \001(\0132\026.protocol."
    "share.AdInfo", 332);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "click.proto", &protobuf_RegisterTypes);
  ClickRequest::default_instance_ = new ClickRequest();
  ClickResponse::default_instance_ = new ClickResponse();
  ClickRequest::default_instance_->InitAsDefaultInstance();
  ClickResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_click_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_click_2eproto {
  StaticDescriptorInitializer_click_2eproto() {
    protobuf_AddDesc_click_2eproto();
  }
} static_descriptor_initializer_click_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int ClickRequest::kCookiesIdFieldNumber;
const int ClickRequest::kAgeFieldNumber;
const int ClickRequest::kSexFieldNumber;
const int ClickRequest::kGeoInfoFieldNumber;
const int ClickRequest::kAdInfoFieldNumber;
#endif  // !_MSC_VER

ClickRequest::ClickRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.share.ClickRequest)
}

void ClickRequest::InitAsDefaultInstance() {
  geoinfo_ = const_cast< ::protocol::share::GeoInfo*>(&::protocol::share::GeoInfo::default_instance());
  adinfo_ = const_cast< ::protocol::share::AdInfo*>(&::protocol::share::AdInfo::default_instance());
}

ClickRequest::ClickRequest(const ClickRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protocol.share.ClickRequest)
}

void ClickRequest::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  cookiesid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  age_ = 0;
  sex_ = 0;
  geoinfo_ = NULL;
  adinfo_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ClickRequest::~ClickRequest() {
  // @@protoc_insertion_point(destructor:protocol.share.ClickRequest)
  SharedDtor();
}

void ClickRequest::SharedDtor() {
  if (cookiesid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete cookiesid_;
  }
  if (this != default_instance_) {
    delete geoinfo_;
    delete adinfo_;
  }
}

void ClickRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClickRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClickRequest_descriptor_;
}

const ClickRequest& ClickRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_click_2eproto();
  return *default_instance_;
}

ClickRequest* ClickRequest::default_instance_ = NULL;

ClickRequest* ClickRequest::New() const {
  return new ClickRequest;
}

void ClickRequest::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<ClickRequest*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 31) {
    ZR_(age_, sex_);
    if (has_cookiesid()) {
      if (cookiesid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        cookiesid_->clear();
      }
    }
    if (has_geoinfo()) {
      if (geoinfo_ != NULL) geoinfo_->::protocol::share::GeoInfo::Clear();
    }
    if (has_adinfo()) {
      if (adinfo_ != NULL) adinfo_->::protocol::share::AdInfo::Clear();
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ClickRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.share.ClickRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string cookiesId = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cookiesid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->cookiesid().data(), this->cookiesid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "cookiesid");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_age;
        break;
      }

      // optional int32 age = 2;
      case 2: {
        if (tag == 16) {
         parse_age:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &age_)));
          set_has_age();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_sex;
        break;
      }

      // optional int32 sex = 3;
      case 3: {
        if (tag == 24) {
         parse_sex:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sex_)));
          set_has_sex();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_geoInfo;
        break;
      }

      // optional .protocol.share.GeoInfo geoInfo = 4;
      case 4: {
        if (tag == 34) {
         parse_geoInfo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_geoinfo()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_adInfo;
        break;
      }

      // optional .protocol.share.AdInfo adInfo = 5;
      case 5: {
        if (tag == 42) {
         parse_adInfo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_adinfo()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.share.ClickRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.share.ClickRequest)
  return false;
#undef DO_
}

void ClickRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.share.ClickRequest)
  // optional string cookiesId = 1;
  if (has_cookiesid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->cookiesid().data(), this->cookiesid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "cookiesid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->cookiesid(), output);
  }

  // optional int32 age = 2;
  if (has_age()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->age(), output);
  }

  // optional int32 sex = 3;
  if (has_sex()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->sex(), output);
  }

  // optional .protocol.share.GeoInfo geoInfo = 4;
  if (has_geoinfo()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->geoinfo(), output);
  }

  // optional .protocol.share.AdInfo adInfo = 5;
  if (has_adinfo()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->adinfo(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:protocol.share.ClickRequest)
}

::google::protobuf::uint8* ClickRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.share.ClickRequest)
  // optional string cookiesId = 1;
  if (has_cookiesid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->cookiesid().data(), this->cookiesid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "cookiesid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->cookiesid(), target);
  }

  // optional int32 age = 2;
  if (has_age()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->age(), target);
  }

  // optional int32 sex = 3;
  if (has_sex()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->sex(), target);
  }

  // optional .protocol.share.GeoInfo geoInfo = 4;
  if (has_geoinfo()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->geoinfo(), target);
  }

  // optional .protocol.share.AdInfo adInfo = 5;
  if (has_adinfo()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->adinfo(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.share.ClickRequest)
  return target;
}

int ClickRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string cookiesId = 1;
    if (has_cookiesid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->cookiesid());
    }

    // optional int32 age = 2;
    if (has_age()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->age());
    }

    // optional int32 sex = 3;
    if (has_sex()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->sex());
    }

    // optional .protocol.share.GeoInfo geoInfo = 4;
    if (has_geoinfo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->geoinfo());
    }

    // optional .protocol.share.AdInfo adInfo = 5;
    if (has_adinfo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->adinfo());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClickRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ClickRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ClickRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ClickRequest::MergeFrom(const ClickRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_cookiesid()) {
      set_cookiesid(from.cookiesid());
    }
    if (from.has_age()) {
      set_age(from.age());
    }
    if (from.has_sex()) {
      set_sex(from.sex());
    }
    if (from.has_geoinfo()) {
      mutable_geoinfo()->::protocol::share::GeoInfo::MergeFrom(from.geoinfo());
    }
    if (from.has_adinfo()) {
      mutable_adinfo()->::protocol::share::AdInfo::MergeFrom(from.adinfo());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ClickRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClickRequest::CopyFrom(const ClickRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClickRequest::IsInitialized() const {

  if (has_adinfo()) {
    if (!this->adinfo().IsInitialized()) return false;
  }
  return true;
}

void ClickRequest::Swap(ClickRequest* other) {
  if (other != this) {
    std::swap(cookiesid_, other->cookiesid_);
    std::swap(age_, other->age_);
    std::swap(sex_, other->sex_);
    std::swap(geoinfo_, other->geoinfo_);
    std::swap(adinfo_, other->adinfo_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ClickRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClickRequest_descriptor_;
  metadata.reflection = ClickRequest_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ClickResponse::kCookiesIdFieldNumber;
const int ClickResponse::kAgeFieldNumber;
const int ClickResponse::kSexFieldNumber;
const int ClickResponse::kGeoInfoFieldNumber;
const int ClickResponse::kAdInfoFieldNumber;
#endif  // !_MSC_VER

ClickResponse::ClickResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.share.ClickResponse)
}

void ClickResponse::InitAsDefaultInstance() {
  geoinfo_ = const_cast< ::protocol::share::GeoInfo*>(&::protocol::share::GeoInfo::default_instance());
  adinfo_ = const_cast< ::protocol::share::AdInfo*>(&::protocol::share::AdInfo::default_instance());
}

ClickResponse::ClickResponse(const ClickResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:protocol.share.ClickResponse)
}

void ClickResponse::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  cookiesid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  age_ = 0;
  sex_ = 0;
  geoinfo_ = NULL;
  adinfo_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ClickResponse::~ClickResponse() {
  // @@protoc_insertion_point(destructor:protocol.share.ClickResponse)
  SharedDtor();
}

void ClickResponse::SharedDtor() {
  if (cookiesid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete cookiesid_;
  }
  if (this != default_instance_) {
    delete geoinfo_;
    delete adinfo_;
  }
}

void ClickResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClickResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClickResponse_descriptor_;
}

const ClickResponse& ClickResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_click_2eproto();
  return *default_instance_;
}

ClickResponse* ClickResponse::default_instance_ = NULL;

ClickResponse* ClickResponse::New() const {
  return new ClickResponse;
}

void ClickResponse::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<ClickResponse*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 31) {
    ZR_(age_, sex_);
    if (has_cookiesid()) {
      if (cookiesid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        cookiesid_->clear();
      }
    }
    if (has_geoinfo()) {
      if (geoinfo_ != NULL) geoinfo_->::protocol::share::GeoInfo::Clear();
    }
    if (has_adinfo()) {
      if (adinfo_ != NULL) adinfo_->::protocol::share::AdInfo::Clear();
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ClickResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.share.ClickResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string cookiesId = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cookiesid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->cookiesid().data(), this->cookiesid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "cookiesid");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_age;
        break;
      }

      // optional int32 age = 2;
      case 2: {
        if (tag == 16) {
         parse_age:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &age_)));
          set_has_age();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_sex;
        break;
      }

      // optional int32 sex = 3;
      case 3: {
        if (tag == 24) {
         parse_sex:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sex_)));
          set_has_sex();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_geoInfo;
        break;
      }

      // optional .protocol.share.GeoInfo geoInfo = 4;
      case 4: {
        if (tag == 34) {
         parse_geoInfo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_geoinfo()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_adInfo;
        break;
      }

      // optional .protocol.share.AdInfo adInfo = 5;
      case 5: {
        if (tag == 42) {
         parse_adInfo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_adinfo()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.share.ClickResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.share.ClickResponse)
  return false;
#undef DO_
}

void ClickResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.share.ClickResponse)
  // required string cookiesId = 1;
  if (has_cookiesid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->cookiesid().data(), this->cookiesid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "cookiesid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->cookiesid(), output);
  }

  // optional int32 age = 2;
  if (has_age()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->age(), output);
  }

  // optional int32 sex = 3;
  if (has_sex()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->sex(), output);
  }

  // optional .protocol.share.GeoInfo geoInfo = 4;
  if (has_geoinfo()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->geoinfo(), output);
  }

  // optional .protocol.share.AdInfo adInfo = 5;
  if (has_adinfo()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->adinfo(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:protocol.share.ClickResponse)
}

::google::protobuf::uint8* ClickResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:protocol.share.ClickResponse)
  // required string cookiesId = 1;
  if (has_cookiesid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->cookiesid().data(), this->cookiesid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "cookiesid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->cookiesid(), target);
  }

  // optional int32 age = 2;
  if (has_age()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->age(), target);
  }

  // optional int32 sex = 3;
  if (has_sex()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->sex(), target);
  }

  // optional .protocol.share.GeoInfo geoInfo = 4;
  if (has_geoinfo()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->geoinfo(), target);
  }

  // optional .protocol.share.AdInfo adInfo = 5;
  if (has_adinfo()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->adinfo(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.share.ClickResponse)
  return target;
}

int ClickResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string cookiesId = 1;
    if (has_cookiesid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->cookiesid());
    }

    // optional int32 age = 2;
    if (has_age()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->age());
    }

    // optional int32 sex = 3;
    if (has_sex()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->sex());
    }

    // optional .protocol.share.GeoInfo geoInfo = 4;
    if (has_geoinfo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->geoinfo());
    }

    // optional .protocol.share.AdInfo adInfo = 5;
    if (has_adinfo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->adinfo());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClickResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ClickResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ClickResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ClickResponse::MergeFrom(const ClickResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_cookiesid()) {
      set_cookiesid(from.cookiesid());
    }
    if (from.has_age()) {
      set_age(from.age());
    }
    if (from.has_sex()) {
      set_sex(from.sex());
    }
    if (from.has_geoinfo()) {
      mutable_geoinfo()->::protocol::share::GeoInfo::MergeFrom(from.geoinfo());
    }
    if (from.has_adinfo()) {
      mutable_adinfo()->::protocol::share::AdInfo::MergeFrom(from.adinfo());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ClickResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClickResponse::CopyFrom(const ClickResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClickResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_adinfo()) {
    if (!this->adinfo().IsInitialized()) return false;
  }
  return true;
}

void ClickResponse::Swap(ClickResponse* other) {
  if (other != this) {
    std::swap(cookiesid_, other->cookiesid_);
    std::swap(age_, other->age_);
    std::swap(sex_, other->sex_);
    std::swap(geoinfo_, other->geoinfo_);
    std::swap(adinfo_, other->adinfo_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ClickResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClickResponse_descriptor_;
  metadata.reflection = ClickResponse_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace share
}  // namespace protocol

// @@protoc_insertion_point(global_scope)
