/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.mtty.protocol;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AdInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6103708168001304921L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AdInfo\",\"namespace\":\"com.mtty.protocol\",\"fields\":[{\"name\":\"areaId\",\"type\":\"string\"},{\"name\":\"advId\",\"type\":\"long\"},{\"name\":\"cpid\",\"type\":\"string\"},{\"name\":\"sid\",\"type\":\"long\"},{\"name\":\"creativeId\",\"type\":\"long\"},{\"name\":\"clickId\",\"type\":\"string\"},{\"name\":\"adxid\",\"type\":\"string\"},{\"name\":\"mid\",\"type\":\"string\"},{\"name\":\"cid\",\"type\":\"string\"},{\"name\":\"pid\",\"type\":\"long\"},{\"name\":\"unionId\",\"type\":\"long\"},{\"name\":\"imp_id\",\"type\":\"string\"},{\"name\":\"landingUrl\",\"type\":\"string\"},{\"name\":\"cost\",\"type\":\"int\"},{\"name\":\"bidPrice\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence areaId;
  @Deprecated public long advId;
  @Deprecated public java.lang.CharSequence cpid;
  @Deprecated public long sid;
  @Deprecated public long creativeId;
  @Deprecated public java.lang.CharSequence clickId;
  @Deprecated public java.lang.CharSequence adxid;
  @Deprecated public java.lang.CharSequence mid;
  @Deprecated public java.lang.CharSequence cid;
  @Deprecated public long pid;
  @Deprecated public long unionId;
  @Deprecated public java.lang.CharSequence imp_id;
  @Deprecated public java.lang.CharSequence landingUrl;
  @Deprecated public int cost;
  @Deprecated public int bidPrice;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public AdInfo() {}

  /**
   * All-args constructor.
   */
  public AdInfo(java.lang.CharSequence areaId, java.lang.Long advId, java.lang.CharSequence cpid, java.lang.Long sid, java.lang.Long creativeId, java.lang.CharSequence clickId, java.lang.CharSequence adxid, java.lang.CharSequence mid, java.lang.CharSequence cid, java.lang.Long pid, java.lang.Long unionId, java.lang.CharSequence imp_id, java.lang.CharSequence landingUrl, java.lang.Integer cost, java.lang.Integer bidPrice) {
    this.areaId = areaId;
    this.advId = advId;
    this.cpid = cpid;
    this.sid = sid;
    this.creativeId = creativeId;
    this.clickId = clickId;
    this.adxid = adxid;
    this.mid = mid;
    this.cid = cid;
    this.pid = pid;
    this.unionId = unionId;
    this.imp_id = imp_id;
    this.landingUrl = landingUrl;
    this.cost = cost;
    this.bidPrice = bidPrice;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return areaId;
    case 1: return advId;
    case 2: return cpid;
    case 3: return sid;
    case 4: return creativeId;
    case 5: return clickId;
    case 6: return adxid;
    case 7: return mid;
    case 8: return cid;
    case 9: return pid;
    case 10: return unionId;
    case 11: return imp_id;
    case 12: return landingUrl;
    case 13: return cost;
    case 14: return bidPrice;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: areaId = (java.lang.CharSequence)value$; break;
    case 1: advId = (java.lang.Long)value$; break;
    case 2: cpid = (java.lang.CharSequence)value$; break;
    case 3: sid = (java.lang.Long)value$; break;
    case 4: creativeId = (java.lang.Long)value$; break;
    case 5: clickId = (java.lang.CharSequence)value$; break;
    case 6: adxid = (java.lang.CharSequence)value$; break;
    case 7: mid = (java.lang.CharSequence)value$; break;
    case 8: cid = (java.lang.CharSequence)value$; break;
    case 9: pid = (java.lang.Long)value$; break;
    case 10: unionId = (java.lang.Long)value$; break;
    case 11: imp_id = (java.lang.CharSequence)value$; break;
    case 12: landingUrl = (java.lang.CharSequence)value$; break;
    case 13: cost = (java.lang.Integer)value$; break;
    case 14: bidPrice = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'areaId' field.
   */
  public java.lang.CharSequence getAreaId() {
    return areaId;
  }

  /**
   * Sets the value of the 'areaId' field.
   * @param value the value to set.
   */
  public void setAreaId(java.lang.CharSequence value) {
    this.areaId = value;
  }

  /**
   * Gets the value of the 'advId' field.
   */
  public java.lang.Long getAdvId() {
    return advId;
  }

  /**
   * Sets the value of the 'advId' field.
   * @param value the value to set.
   */
  public void setAdvId(java.lang.Long value) {
    this.advId = value;
  }

  /**
   * Gets the value of the 'cpid' field.
   */
  public java.lang.CharSequence getCpid() {
    return cpid;
  }

  /**
   * Sets the value of the 'cpid' field.
   * @param value the value to set.
   */
  public void setCpid(java.lang.CharSequence value) {
    this.cpid = value;
  }

  /**
   * Gets the value of the 'sid' field.
   */
  public java.lang.Long getSid() {
    return sid;
  }

  /**
   * Sets the value of the 'sid' field.
   * @param value the value to set.
   */
  public void setSid(java.lang.Long value) {
    this.sid = value;
  }

  /**
   * Gets the value of the 'creativeId' field.
   */
  public java.lang.Long getCreativeId() {
    return creativeId;
  }

  /**
   * Sets the value of the 'creativeId' field.
   * @param value the value to set.
   */
  public void setCreativeId(java.lang.Long value) {
    this.creativeId = value;
  }

  /**
   * Gets the value of the 'clickId' field.
   */
  public java.lang.CharSequence getClickId() {
    return clickId;
  }

  /**
   * Sets the value of the 'clickId' field.
   * @param value the value to set.
   */
  public void setClickId(java.lang.CharSequence value) {
    this.clickId = value;
  }

  /**
   * Gets the value of the 'adxid' field.
   */
  public java.lang.CharSequence getAdxid() {
    return adxid;
  }

  /**
   * Sets the value of the 'adxid' field.
   * @param value the value to set.
   */
  public void setAdxid(java.lang.CharSequence value) {
    this.adxid = value;
  }

  /**
   * Gets the value of the 'mid' field.
   */
  public java.lang.CharSequence getMid() {
    return mid;
  }

  /**
   * Sets the value of the 'mid' field.
   * @param value the value to set.
   */
  public void setMid(java.lang.CharSequence value) {
    this.mid = value;
  }

  /**
   * Gets the value of the 'cid' field.
   */
  public java.lang.CharSequence getCid() {
    return cid;
  }

  /**
   * Sets the value of the 'cid' field.
   * @param value the value to set.
   */
  public void setCid(java.lang.CharSequence value) {
    this.cid = value;
  }

  /**
   * Gets the value of the 'pid' field.
   */
  public java.lang.Long getPid() {
    return pid;
  }

  /**
   * Sets the value of the 'pid' field.
   * @param value the value to set.
   */
  public void setPid(java.lang.Long value) {
    this.pid = value;
  }

  /**
   * Gets the value of the 'unionId' field.
   */
  public java.lang.Long getUnionId() {
    return unionId;
  }

  /**
   * Sets the value of the 'unionId' field.
   * @param value the value to set.
   */
  public void setUnionId(java.lang.Long value) {
    this.unionId = value;
  }

  /**
   * Gets the value of the 'imp_id' field.
   */
  public java.lang.CharSequence getImpId() {
    return imp_id;
  }

  /**
   * Sets the value of the 'imp_id' field.
   * @param value the value to set.
   */
  public void setImpId(java.lang.CharSequence value) {
    this.imp_id = value;
  }

  /**
   * Gets the value of the 'landingUrl' field.
   */
  public java.lang.CharSequence getLandingUrl() {
    return landingUrl;
  }

  /**
   * Sets the value of the 'landingUrl' field.
   * @param value the value to set.
   */
  public void setLandingUrl(java.lang.CharSequence value) {
    this.landingUrl = value;
  }

  /**
   * Gets the value of the 'cost' field.
   */
  public java.lang.Integer getCost() {
    return cost;
  }

  /**
   * Sets the value of the 'cost' field.
   * @param value the value to set.
   */
  public void setCost(java.lang.Integer value) {
    this.cost = value;
  }

  /**
   * Gets the value of the 'bidPrice' field.
   */
  public java.lang.Integer getBidPrice() {
    return bidPrice;
  }

  /**
   * Sets the value of the 'bidPrice' field.
   * @param value the value to set.
   */
  public void setBidPrice(java.lang.Integer value) {
    this.bidPrice = value;
  }

  /**
   * Creates a new AdInfo RecordBuilder.
   * @return A new AdInfo RecordBuilder
   */
  public static com.mtty.protocol.AdInfo.Builder newBuilder() {
    return new com.mtty.protocol.AdInfo.Builder();
  }
  
  /**
   * Creates a new AdInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AdInfo RecordBuilder
   */
  public static com.mtty.protocol.AdInfo.Builder newBuilder(com.mtty.protocol.AdInfo.Builder other) {
    return new com.mtty.protocol.AdInfo.Builder(other);
  }
  
  /**
   * Creates a new AdInfo RecordBuilder by copying an existing AdInfo instance.
   * @param other The existing instance to copy.
   * @return A new AdInfo RecordBuilder
   */
  public static com.mtty.protocol.AdInfo.Builder newBuilder(com.mtty.protocol.AdInfo other) {
    return new com.mtty.protocol.AdInfo.Builder(other);
  }
  
  /**
   * RecordBuilder for AdInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AdInfo>
    implements org.apache.avro.data.RecordBuilder<AdInfo> {

    private java.lang.CharSequence areaId;
    private long advId;
    private java.lang.CharSequence cpid;
    private long sid;
    private long creativeId;
    private java.lang.CharSequence clickId;
    private java.lang.CharSequence adxid;
    private java.lang.CharSequence mid;
    private java.lang.CharSequence cid;
    private long pid;
    private long unionId;
    private java.lang.CharSequence imp_id;
    private java.lang.CharSequence landingUrl;
    private int cost;
    private int bidPrice;

    /** Creates a new Builder */
    private Builder() {
      super(com.mtty.protocol.AdInfo.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mtty.protocol.AdInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.areaId)) {
        this.areaId = data().deepCopy(fields()[0].schema(), other.areaId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.advId)) {
        this.advId = data().deepCopy(fields()[1].schema(), other.advId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.cpid)) {
        this.cpid = data().deepCopy(fields()[2].schema(), other.cpid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.sid)) {
        this.sid = data().deepCopy(fields()[3].schema(), other.sid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.creativeId)) {
        this.creativeId = data().deepCopy(fields()[4].schema(), other.creativeId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.clickId)) {
        this.clickId = data().deepCopy(fields()[5].schema(), other.clickId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.adxid)) {
        this.adxid = data().deepCopy(fields()[6].schema(), other.adxid);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.mid)) {
        this.mid = data().deepCopy(fields()[7].schema(), other.mid);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.cid)) {
        this.cid = data().deepCopy(fields()[8].schema(), other.cid);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.pid)) {
        this.pid = data().deepCopy(fields()[9].schema(), other.pid);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.unionId)) {
        this.unionId = data().deepCopy(fields()[10].schema(), other.unionId);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.imp_id)) {
        this.imp_id = data().deepCopy(fields()[11].schema(), other.imp_id);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.landingUrl)) {
        this.landingUrl = data().deepCopy(fields()[12].schema(), other.landingUrl);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.cost)) {
        this.cost = data().deepCopy(fields()[13].schema(), other.cost);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.bidPrice)) {
        this.bidPrice = data().deepCopy(fields()[14].schema(), other.bidPrice);
        fieldSetFlags()[14] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing AdInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mtty.protocol.AdInfo other) {
            super(com.mtty.protocol.AdInfo.SCHEMA$);
      if (isValidValue(fields()[0], other.areaId)) {
        this.areaId = data().deepCopy(fields()[0].schema(), other.areaId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.advId)) {
        this.advId = data().deepCopy(fields()[1].schema(), other.advId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.cpid)) {
        this.cpid = data().deepCopy(fields()[2].schema(), other.cpid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.sid)) {
        this.sid = data().deepCopy(fields()[3].schema(), other.sid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.creativeId)) {
        this.creativeId = data().deepCopy(fields()[4].schema(), other.creativeId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.clickId)) {
        this.clickId = data().deepCopy(fields()[5].schema(), other.clickId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.adxid)) {
        this.adxid = data().deepCopy(fields()[6].schema(), other.adxid);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.mid)) {
        this.mid = data().deepCopy(fields()[7].schema(), other.mid);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.cid)) {
        this.cid = data().deepCopy(fields()[8].schema(), other.cid);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.pid)) {
        this.pid = data().deepCopy(fields()[9].schema(), other.pid);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.unionId)) {
        this.unionId = data().deepCopy(fields()[10].schema(), other.unionId);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.imp_id)) {
        this.imp_id = data().deepCopy(fields()[11].schema(), other.imp_id);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.landingUrl)) {
        this.landingUrl = data().deepCopy(fields()[12].schema(), other.landingUrl);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.cost)) {
        this.cost = data().deepCopy(fields()[13].schema(), other.cost);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.bidPrice)) {
        this.bidPrice = data().deepCopy(fields()[14].schema(), other.bidPrice);
        fieldSetFlags()[14] = true;
      }
    }

    /**
      * Gets the value of the 'areaId' field.
      * @return The value.
      */
    public java.lang.CharSequence getAreaId() {
      return areaId;
    }

    /**
      * Sets the value of the 'areaId' field.
      * @param value The value of 'areaId'.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder setAreaId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.areaId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'areaId' field has been set.
      * @return True if the 'areaId' field has been set, false otherwise.
      */
    public boolean hasAreaId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'areaId' field.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder clearAreaId() {
      areaId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'advId' field.
      * @return The value.
      */
    public java.lang.Long getAdvId() {
      return advId;
    }

    /**
      * Sets the value of the 'advId' field.
      * @param value The value of 'advId'.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder setAdvId(long value) {
      validate(fields()[1], value);
      this.advId = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'advId' field has been set.
      * @return True if the 'advId' field has been set, false otherwise.
      */
    public boolean hasAdvId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'advId' field.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder clearAdvId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'cpid' field.
      * @return The value.
      */
    public java.lang.CharSequence getCpid() {
      return cpid;
    }

    /**
      * Sets the value of the 'cpid' field.
      * @param value The value of 'cpid'.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder setCpid(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.cpid = value;
      fieldSetFlags()[2] = true;
      return this; 
    }

    /**
      * Checks whether the 'cpid' field has been set.
      * @return True if the 'cpid' field has been set, false otherwise.
      */
    public boolean hasCpid() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'cpid' field.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder clearCpid() {
      cpid = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'sid' field.
      * @return The value.
      */
    public java.lang.Long getSid() {
      return sid;
    }

    /**
      * Sets the value of the 'sid' field.
      * @param value The value of 'sid'.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder setSid(long value) {
      validate(fields()[3], value);
      this.sid = value;
      fieldSetFlags()[3] = true;
      return this; 
    }

    /**
      * Checks whether the 'sid' field has been set.
      * @return True if the 'sid' field has been set, false otherwise.
      */
    public boolean hasSid() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'sid' field.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder clearSid() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'creativeId' field.
      * @return The value.
      */
    public java.lang.Long getCreativeId() {
      return creativeId;
    }

    /**
      * Sets the value of the 'creativeId' field.
      * @param value The value of 'creativeId'.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder setCreativeId(long value) {
      validate(fields()[4], value);
      this.creativeId = value;
      fieldSetFlags()[4] = true;
      return this; 
    }

    /**
      * Checks whether the 'creativeId' field has been set.
      * @return True if the 'creativeId' field has been set, false otherwise.
      */
    public boolean hasCreativeId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'creativeId' field.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder clearCreativeId() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'clickId' field.
      * @return The value.
      */
    public java.lang.CharSequence getClickId() {
      return clickId;
    }

    /**
      * Sets the value of the 'clickId' field.
      * @param value The value of 'clickId'.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder setClickId(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.clickId = value;
      fieldSetFlags()[5] = true;
      return this; 
    }

    /**
      * Checks whether the 'clickId' field has been set.
      * @return True if the 'clickId' field has been set, false otherwise.
      */
    public boolean hasClickId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'clickId' field.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder clearClickId() {
      clickId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'adxid' field.
      * @return The value.
      */
    public java.lang.CharSequence getAdxid() {
      return adxid;
    }

    /**
      * Sets the value of the 'adxid' field.
      * @param value The value of 'adxid'.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder setAdxid(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.adxid = value;
      fieldSetFlags()[6] = true;
      return this; 
    }

    /**
      * Checks whether the 'adxid' field has been set.
      * @return True if the 'adxid' field has been set, false otherwise.
      */
    public boolean hasAdxid() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'adxid' field.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder clearAdxid() {
      adxid = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'mid' field.
      * @return The value.
      */
    public java.lang.CharSequence getMid() {
      return mid;
    }

    /**
      * Sets the value of the 'mid' field.
      * @param value The value of 'mid'.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder setMid(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.mid = value;
      fieldSetFlags()[7] = true;
      return this; 
    }

    /**
      * Checks whether the 'mid' field has been set.
      * @return True if the 'mid' field has been set, false otherwise.
      */
    public boolean hasMid() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'mid' field.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder clearMid() {
      mid = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'cid' field.
      * @return The value.
      */
    public java.lang.CharSequence getCid() {
      return cid;
    }

    /**
      * Sets the value of the 'cid' field.
      * @param value The value of 'cid'.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder setCid(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.cid = value;
      fieldSetFlags()[8] = true;
      return this; 
    }

    /**
      * Checks whether the 'cid' field has been set.
      * @return True if the 'cid' field has been set, false otherwise.
      */
    public boolean hasCid() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'cid' field.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder clearCid() {
      cid = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'pid' field.
      * @return The value.
      */
    public java.lang.Long getPid() {
      return pid;
    }

    /**
      * Sets the value of the 'pid' field.
      * @param value The value of 'pid'.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder setPid(long value) {
      validate(fields()[9], value);
      this.pid = value;
      fieldSetFlags()[9] = true;
      return this; 
    }

    /**
      * Checks whether the 'pid' field has been set.
      * @return True if the 'pid' field has been set, false otherwise.
      */
    public boolean hasPid() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'pid' field.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder clearPid() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'unionId' field.
      * @return The value.
      */
    public java.lang.Long getUnionId() {
      return unionId;
    }

    /**
      * Sets the value of the 'unionId' field.
      * @param value The value of 'unionId'.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder setUnionId(long value) {
      validate(fields()[10], value);
      this.unionId = value;
      fieldSetFlags()[10] = true;
      return this; 
    }

    /**
      * Checks whether the 'unionId' field has been set.
      * @return True if the 'unionId' field has been set, false otherwise.
      */
    public boolean hasUnionId() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'unionId' field.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder clearUnionId() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'imp_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getImpId() {
      return imp_id;
    }

    /**
      * Sets the value of the 'imp_id' field.
      * @param value The value of 'imp_id'.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder setImpId(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.imp_id = value;
      fieldSetFlags()[11] = true;
      return this; 
    }

    /**
      * Checks whether the 'imp_id' field has been set.
      * @return True if the 'imp_id' field has been set, false otherwise.
      */
    public boolean hasImpId() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'imp_id' field.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder clearImpId() {
      imp_id = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'landingUrl' field.
      * @return The value.
      */
    public java.lang.CharSequence getLandingUrl() {
      return landingUrl;
    }

    /**
      * Sets the value of the 'landingUrl' field.
      * @param value The value of 'landingUrl'.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder setLandingUrl(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.landingUrl = value;
      fieldSetFlags()[12] = true;
      return this; 
    }

    /**
      * Checks whether the 'landingUrl' field has been set.
      * @return True if the 'landingUrl' field has been set, false otherwise.
      */
    public boolean hasLandingUrl() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'landingUrl' field.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder clearLandingUrl() {
      landingUrl = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'cost' field.
      * @return The value.
      */
    public java.lang.Integer getCost() {
      return cost;
    }

    /**
      * Sets the value of the 'cost' field.
      * @param value The value of 'cost'.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder setCost(int value) {
      validate(fields()[13], value);
      this.cost = value;
      fieldSetFlags()[13] = true;
      return this; 
    }

    /**
      * Checks whether the 'cost' field has been set.
      * @return True if the 'cost' field has been set, false otherwise.
      */
    public boolean hasCost() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'cost' field.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder clearCost() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'bidPrice' field.
      * @return The value.
      */
    public java.lang.Integer getBidPrice() {
      return bidPrice;
    }

    /**
      * Sets the value of the 'bidPrice' field.
      * @param value The value of 'bidPrice'.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder setBidPrice(int value) {
      validate(fields()[14], value);
      this.bidPrice = value;
      fieldSetFlags()[14] = true;
      return this; 
    }

    /**
      * Checks whether the 'bidPrice' field has been set.
      * @return True if the 'bidPrice' field has been set, false otherwise.
      */
    public boolean hasBidPrice() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'bidPrice' field.
      * @return This builder.
      */
    public com.mtty.protocol.AdInfo.Builder clearBidPrice() {
      fieldSetFlags()[14] = false;
      return this;
    }

    @Override
    public AdInfo build() {
      try {
        AdInfo record = new AdInfo();
        record.areaId = fieldSetFlags()[0] ? this.areaId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.advId = fieldSetFlags()[1] ? this.advId : (java.lang.Long) defaultValue(fields()[1]);
        record.cpid = fieldSetFlags()[2] ? this.cpid : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.sid = fieldSetFlags()[3] ? this.sid : (java.lang.Long) defaultValue(fields()[3]);
        record.creativeId = fieldSetFlags()[4] ? this.creativeId : (java.lang.Long) defaultValue(fields()[4]);
        record.clickId = fieldSetFlags()[5] ? this.clickId : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.adxid = fieldSetFlags()[6] ? this.adxid : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.mid = fieldSetFlags()[7] ? this.mid : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.cid = fieldSetFlags()[8] ? this.cid : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.pid = fieldSetFlags()[9] ? this.pid : (java.lang.Long) defaultValue(fields()[9]);
        record.unionId = fieldSetFlags()[10] ? this.unionId : (java.lang.Long) defaultValue(fields()[10]);
        record.imp_id = fieldSetFlags()[11] ? this.imp_id : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.landingUrl = fieldSetFlags()[12] ? this.landingUrl : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.cost = fieldSetFlags()[13] ? this.cost : (java.lang.Integer) defaultValue(fields()[13]);
        record.bidPrice = fieldSetFlags()[14] ? this.bidPrice : (java.lang.Integer) defaultValue(fields()[14]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
