/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mtty_cypher_AliBinaryEscaper */

#ifndef _Included_com_mtty_cypher_AliBinaryEscaper
#define _Included_com_mtty_cypher_AliBinaryEscaper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mtty_cypher_AliBinaryEscaper
 * Method:    unescape
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_mtty_cypher_AliBinaryEscaper_unescape
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_mtty_cypher_AliBinaryEscaper
 * Method:    escape
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_mtty_cypher_AliBinaryEscaper_escape
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
